[package]
name = "actually_mysql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.30"
tabled = "0.10.0"
pest = "2.5.4"
pest_derive = "2.5.4"
